### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by afasijbfk** [yjch00/PLURAL#1]
Hello, may I ask if you can provide the preprocessed dataset?

**Comment by afasijbfk** [comment]
Or could you show us some data samples. Thanks very much.

**Comment by afasijbfk** [comment]
> Or could you show us some data samples. Thanks very much.

data_dir=/data/yjcho/PLURAL/data/
data=${data_dir}/mimic_diff_vqa_train.tsv,${data_dir}/mimic_diff_vqa_valid.tsv

**Comment by yjch00** [comment]
Due to policy reasons, we are unable to provide the dataset. However, you can refer to the following file to create the data yourself: data_preprocess.ipynb.
